### ISSUE TITLE
Not working 'workdir'

### ISSUE THREAD

**Issue by tomoyk** [goreleaser/goreleaser-action#115]
I tried to use `workdir` option on CI. But not worked the option.

The message `📂 Using XXX as working directory...` is not outputted.

https://github.com/goreleaser/goreleaser-action/blob/e198786300556bb65479bb091b8a0f52c93d67f5/lib/main.js#L35-L38

Screenshot:

![image](https://user-images.githubusercontent.com/2428176/76704778-a7326900-671e-11ea-85a6-a38e7178e840.png)

workflow:

```
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
          workdir: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Please let me know  if you find any other solutions for that.
