### ISSUE TITLE
stuck in "snapshot" even though command is "release"

### ISSUE THREAD

**Issue by tsal** [goreleaser/goreleaser-action#121]
Steps:
1. Create action using defaults
```
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v1.3.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
2. Create .goreleaser.yml with mostly defaults (path defined for main)

Expectation:
GitHub release created

Outcome:
```
🏃 Running GoReleaser...
/home/runner/work/_temp/9ea6a3b8-6367-433e-9f2f-54a5fcc8cd99/goreleaser release --rm-dist --snapshot
```

Why is it adding `--snapshot` ?

**Comment by tsal** [comment]
Since the goreleaser documentation itself is the problem, closing this.

**Comment by crazy-max** [comment]
This has been discussed #77 and #95

**Comment by remorses** [comment]
I have read the code added in pull #95 and found out that if you skip the `release` command it won't force a snapshot (very arbitrary and non sense imho)

I use the following to add a release for the last tag
```yml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
