### ISSUE TITLE
Parse goreleaser version as semver

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser-action#157]
Version currently seems to be parsed [as fixed string](). This leaves users with two sub-optimal options of either setting version to `latest`, or to an exact patch version (`vMAJOR.MINOR.PATCH`).

1. When they set it to latest they risk broken releases once goreleaser cuts new major version.
2. When they set it to exact patch version they don't receive any updates, including potentially important security updates.

I believe it would be best if version was parsed as semver and specifying just major version was allowed, e.g.

```yml
      -
        name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0
          args: release --rm-dist
```
That way users would receive any `v0.X.Y` updates, but (crucially) _not_ potentially breaking `v1`.

This also aligns with how version of GitHub Actions works.

Once this is supported I'd also go as far as recommending this as the default option by updating the example in the Readme, which currently has `latest`.
