### ISSUE TITLE
Github Action Plugin is failing validating the signed goreleaser binary

### ISSUE THREAD

**Issue by crosseyed** [goreleaser/goreleaser-action#167]
Hello,
Using the gorelaser github action.

I'm getting the following error
### Error
```
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
##[error]The process '/usr/bin/gpg' failed with exit code 2
```

### Full Error
```
✅ GoReleaser version found: v0.132.1
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.132.1/goreleaser_Linux_x86_64.tar.gz...
📦 Extracting GoReleaser...
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/bccc5fef-9525-4910-9f30-4acebe213f61 -f /tmp/goreleaser-OwL3RR/goreleaser_Linux_x86_64.tar.gz
✅ v1.1.0 tag found for commit 7566ebc
🔑 Importing signing key...
/usr/bin/gpg --import /home/runner/key.asc
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
##[error]The process '/usr/bin/gpg' failed with exit code 2
```

### Github Action Configuration
```yaml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
name: Create Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go 1.14.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      -
        name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --skip-sign
          key: ${{ secrets.RELEASE_KEY }}
```

### Failing Github Action
[https://github.com/crosseyed/prjstart/runs/619750827?check_suite_focus=true](https://github.com/crosseyed/prjstart/runs/619750827?check_suite_focus=true)
