### ISSUE TITLE
Unable to include folder in archive

### ISSUE THREAD

**Issue by Edwin-Luijten** [goreleaser/goreleaser-action#169]
I have the following project structure:
```
- server
  - main.go
  - public
  - .goreleaser.yml
- frontend
```
When I run goreleaser locally ```bin/goreleaser --snapshot --skip-publish --rm-dist``` it creates an archive with my specified folder, below a part of the config:
```
...
archives:
  -
    name_template: "{{ .ProjectName }}_{{ tolower .Os }}_{{ tolower .Arch }}"
    files:
      - public/**/*
...
```

But when the github action is creating a build, it does not include the public folder in the archive.
I specified the working directory:
```
-
        name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          workdir: server
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Find below the action: https://github.com/q-assistant/controller/actions/runs/89358207
