### ISSUE TITLE
Using release drafter in combination with goreleaser

### ISSUE THREAD

**Issue by arminc** [goreleaser/goreleaser-action#207]
I am using https://github.com/marketplace/actions/release-drafter to create a draft release for every PR. When I do a release with goreleaser with changelog skip to true it creates a new release instead of using the draft.
I was wondering if this should work and if so how? If not then it means I either need to accept I can only use goreleasers commits or maybe try to use https://github.com/buchanae/github-release-notes as input? Any other solutions or examples where people use PR for notes with goreleaser?

**Comment by crazy-max** [comment]
Hi @arminc, do you have a link to your repo?

**Comment by arminc** [comment]
@crazy-max Here it is: https://github.com/arminc/k8s-platform-lcm

**Comment by crazy-max** [comment]
@arminc I think it's a release-drafter constraint and you should also apply this step in your `release.yml` workflow. Something like that:

```yaml
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
    - name: Publish Release Notes
      uses: release-drafter/release-drafter@f677696
      with:
        publish: ${{ steps.check-version.outputs.tag != '' }}
        tag: ${{ steps.check-version.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
```

See also https://github.com/release-drafter/release-drafter/pull/424#issuecomment-598830640

**Comment by arminc** [comment]
I have tried it out but it doesn't seem to work out. I will do some more testing or open an issue with release-drafter.
I find it interesting that goreleaser doesn't "recognize" or do anything with the draft. When I was using the travis-ci deploy provider for github it actually "converted or used, not sure which it was" the draft to make it a proper release with binaries included. I am not sure what they were doing that is why I assumed it had to do something with goreleaser.

**Comment by arminc** [comment]
@crazy-max Thanks for the quick help. As you can see in this issue https://github.com/release-drafter/release-drafter/issues/542 release drafter currently can't do a publish. In my opinion that kind of makes sense. Shouldn't it be goreleasers job to use a draft if it is already there?

**Comment by jetersen** [comment]
release-drafter/release-drafter/pull/546 should greatly improve the experience.

You can even write something like this after the PR is merged:

```yaml
name: Release Drafter

on:
  push:
    branches:
      - master
    tags:
      - v*
    release:
      types: [deleted]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ contains(github.ref, "ref/tags") }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

With the following below it will allow you to publish on tags and automatically redraft and republish any deleted any deleted releases.

```yaml
on:
  push:
    tags:
      - v*
    release:
      types: [deleted]
```
