### ISSUE TITLE
Failing builds with snaps snapcore/action-build github action

### ISSUE THREAD

**Issue by wakatara** [goreleaser/goreleaser-action#215]
First off thanks for creating this action and workign on goreleaser. I already have releases being built on auto for vx.x.x tags and a homebrew formula out there which was very painless. Merci for all this hard work. 

I am not trying to get builds for snap (and eventually flatpak) working to make life easier for my friends in linux land. For some reason I keep having a fail on the snapcraft goreleaser section though am failing to understand why as I am using a handy *other* github action that installs snap and lxd for me. 

I [opened an issue with the author of that action here](https://github.com/snapcore/action-build/issues/2) but he thinks it is something goreleaser action related. I think getting this sorted would be great for go folks wanting to release easily into linux so just trying to stickhandle sorting this out (and will write a blog post on it later so people can find a formula on it.).

I altered my release.yml file to look like this:
``` yaml
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Snap Action Build
        uses: snapcore/action-build@v1
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_HARSH_SECRET }}
```

I've lifted the snapcraft section out of the goreleaser.yml and hjave proper keys so pretty sure that's working. But just wondering if there is something specific the action is expecting in terms of snap installation on the GH instance. 

The author mentioned that a number of things happen with the action as it is non-trivial to get working:

> 1. change ownership of / to root:root, since GH's VM image has weird permissions.
> 2. install snapd with apt.
> 3. remove the lxd and lxd-client` apt packages, so they don't conflict with the newer snap version.
> 4. install the lxd snap.
> 5. run sudo lxd init --auto to set up a default configuration for LXD.
> 6. add the CI user to the lxd group.
> 7. install the snapcraft snap
> 8. set SNAPCRAFT_BUILD_ENVIRONMENT=lxd in the environment
> 9. invoke Snapcraft with sg lxd -c snapcraft to pick up the new group membership needed to create LXD containers.

Is there anything in there you see that might cause this to fail from the goreleaser action? Obviosuly jsut trying to get everthing up and working in an automated hands-off fashion.  =] 

thanks!
Daryl.
