### ISSUE TITLE
Can't use alternative checkout path

### ISSUE THREAD

**Issue by abatilo** [goreleaser/goreleaser-action#224]
https://github.com/goreleaser/goreleaser-action/blob/62b67a060c61c098976b8f411b75a003f009c3bc/dist/index.js#L1422-L1428

If I checkout my code into another directory so that I can set a `$GOPATH`:
```
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/abatilo/my_repository
```

Since it appears that this action tries to get the git hash BEFORE doing any changing of directories, there is no `.git` directory in the starting directory of the action.
