### ISSUE TITLE
FreeBSD/arm64 is not supported by Go

### ISSUE THREAD

**Issue by CatTheHacker** [goreleaser/goreleaser-action#225]
Action fails during build trying to build FreeBSD/arm64:
```yaml
⨯ release failed after 172.59s error=failed to build for freebsd_arm64: cmd/go: unsupported GOOS/GOARCH pair freebsd/arm64
```

workflow step
```yaml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.1.1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

config
```yaml
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - replacements:
      darwin: macOS

    format: zip

    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```
