### ISSUE TITLE
How to build for Windows

### ISSUE THREAD

**Issue by abergmeier** [goreleaser/goreleaser-action#231]
Naively I thought that adding a file to my repo would make goreleaser build for Windows, too:

```
# .goreleaser.yml
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
```

It seems however that goreleaser Action does not pick up that file. How can I tell goreleaser to also build for Windows then?
