### ISSUE TITLE
Can't use --release-notes flag with process substitution

### ISSUE THREAD

**Issue by talal** [goreleaser/goreleaser-action#232]
Hi,

I would like to use custom release notes by using process substitution as describe [here](https://goreleaser.com/customization/release/#custom-release-notes).

I have written a [simple tool](https://github.com/sapcc/limesctl/blob/master/tools/releaseinfo/main.go) that extracts the release info for a specific tag from my `CHANGELOG.md` file.

Locally this works as expected:

```sh
$ goreleaser --snapshot --skip-publish --rm-dist --release-notes <(go run tools/releaseinfo/main.go CHANGELOG.md "$(git describe --tags --abbrev=0)")
...

• generating changelog
      • loaded custom release notes file=/dev/fd/63
      • pipe skipped              error=not available for snapshots
...
```

However, I can't get this to work with goreleaser-action. Here is my [GH workflow](https://github.com/sapcc/limesctl/blob/master/.github/workflows/release.yml) and [GoReleaser config](https://github.com/sapcc/limesctl/blob/master/.goreleaser.yml) for your reference.

I have tried direct direct substitution like:

```yaml
 - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
         version: latest
         args: release --rm-dist --release-notes <(go run tools/releaseinfo/main.go CHANGELOG.md "$(git describe --tags --abbrev=0)")
```

and I have tried writing the date to a file first and then using `cat` like:

```yaml
- name: Get releaseinfo
     run: |
       mkdir build/
       go run tools/releaseinfo/main.go CHANGELOG.md "$(git describe --tags --abbrev=0)" > build/releaseinfo

- name: Run GoReleaser
     uses: goreleaser/goreleaser-action@v2
     with:
       version: latest
       args: release --rm-dist --release-notes <(cat build/releaseinfo)
```

but neither of the above methods work and I get `no such file or directory` errors like: 

```
⨯ release failed after 4.10s error=open <(cat: no such file or directory
```

Can you tell what is the correct way of using process substitution and the `--release-notes` flag with goreleaser-action?

**Comment by crazy-max** [comment]
Hi @talal,

`args` input does not support process substitution but you can use a file as parameter:

```
- name: Run GoReleaser
     uses: goreleaser/goreleaser-action@v2
     with:
       version: latest
       args: release --rm-dist --release-notes ./build/releaseinfo
```
