### ISSUE TITLE
Cross compile with CGO depencies?

### ISSUE THREAD

**Issue by jimafisk** [goreleaser/goreleaser-action#233]
I've been using this project to build linux, darwin, and windows binaries and it's worked great (thank you!). However, recently I've added a module that relies on cgo, which to my understanding is not directly supported by goreleaser itself. Is it possible to use this GitHub Action with cgo, or is that something I'll need to roll my own Docker container for?

<details>
<summary>Some additional build details in case that's helpful</summary>
<br>

My `.goreleaser.yml` has:

```yml
builds:
- env:
  - CGO_ENABLED=1
```
Failing build: https://github.com/plentico/plenti/runs/946698117#step:8:128

</details>

**Comment by crazy-max** [comment]
Hi @jimafisk,

What you can do in this case is installing the gcc multilib:

```yaml
      -
        name: GCC multilib
        run: |
          sudo apt-get install gcc-multilib g++-multilib
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --debug
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

**Comment by jimafisk** [comment]
Thanks for the quick response @crazy-max! I'm still having a little trouble figuring this out, after installing the multilib packages I get `could not determine kind of name for C.AI_MASK` errors on the latest build: https://github.com/plentico/plenti/runs/954407001#step:9:119

Do I need to specifically tell the cross-compiler to use something other than default gcc in `.goreleaser.yml`? 
```
builds:
- env:
  - CGO_ENABLED=1
  - CC=something?
```
Locally on my Ubuntu 18.04 laptop I tried referencing `gcc-multilib` and `g++-multilib` but they are not found in $PATH even though I apt-get installed them. Thank you for the help!

**Comment by jimafisk** [comment]
It seems like [OSXCross](https://github.com/tpoechtrager/osxcross
) is the best way build darwin (Mac) binaries from a linux machine based on posts like [this](https://tenbaht.github.io/sduino/developer/cross-compile-for-osx/) and [this](https://fyne.io/develop/cross-compiling.html). Locally on my Ubuntu 18.04 laptop I was able to accomplish this with the following steps:

1. Download OSXCross: https://github.com/tpoechtrager/osxcross/archive/master.zip
2. Unzip the downloaded archive from step 1 so the project lives at `~/Downloads/osxcross-master/`
3. Login and download XCode from https://developer.apple.com/download/more/ (version 11.6 worked for me, the beta release for 12 and even some of the older versions like [mentioned here](https://github.com/tpoechtrager/osxcross/issues/160#issuecomment-445206938) did not)
4. Move the downloaded archive from step 3 so it lives at `~/Downloads/osxcross-master/Xcode_11.6.xip`
5. Move into the OSXCross folder (`cd ~/Downloads/osxcross-master`) and run `./tools/gen_sdk_package_pbzx.sh Xcode_11.6.xip` which creates the SDK that lives at `~/Downloads/osxcross-master/MacOSX10.15.sdk.tar.xz`. **Note:** I would have loved to used a precompiled SDK from https://github.com/phracker/MacOSX-SDKs but using those gave me the following errors:
```
# crypto/x509
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
# rogchap.com/v8go
In file included from v8go.cc:3:
../../../../go/pkg/mod/rogchap.com/v8go@v0.2.0/deps/include/v8.h:23:10: fatal error: 'type_traits' file not found
```
6. Move the SDK created in step 5 into the "tarballs" directory: `mv ~/Downloads/osxcross-master/MacOSX10.15.sdk.tar.xz ~/Downloads/osxcross-master/tarballs/MacOSX10.15.sdk.tar.xz`
7. While still in `~/Downloads/osxcross-master/` run the build: `./build.sh`. That should create a "target" directory with a bunch of files and folders in it, one of which is `~/Downloads/osxcross-master/target/bin/` that contains various cross-compilers, including `o64-clang` that we'll be using. You can move the "target" directory into your path or just reference directly like I do below.

After completing the steps above, you should be able to create a darwin binary using the following command (Update the paths to use your computer's username, not jimafisk):
```
env GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 CC=/home/jimafisk/Downloads/osxcross-master/target/bin/o64-clang CXX=/home/jimafisk/Downloads/osxcross-master/target/bin/o64-clang++ go build -ldflags -s
```

**Note:** Before adding the `-ldflags -s` flags as [recommended here](https://github.com/golang/go/issues/19734#issuecomment-289822644) I was getting the following error:
```
# plenti
/usr/local/go/pkg/tool/linux_amd64/link: /usr/local/go/pkg/tool/linux_amd64/link: running dsymutil failed: exec: "dsymutil": executable file not found in $PATH
```

**Comment by crazy-max** [comment]
@jimafisk Ok that looks hacky :sweat_smile: and I don't think something will be changed in our action to handle this. AFAIK [GoReleaser doesn't support CGO](https://goreleaser.com/limitations/cgo/). See also goreleaser/goreleaser#708. Thoughts @caarlos0?

**Comment by jimafisk** [comment]
Hahah yeah it's not the nicest thing ever. I did manage to pull it into a GitHub Action step that works:
```
-
  name: OSXCross for CGO Support
  run: |
    mkdir ../plenti-osxcross
    git clone https://github.com/plentico/plenti-osxcross.git ../plenti-osxcross/target
```

I set up [this repo](https://github.com/plentico/plenti-osxcross) which is the "target" directory that's created in step 7 above. If someone else is interested in setting something like this up, keep in mind that "target" directory has hardcoded paths (you can't create it in one folder then move it somewhere else and have it continue working). I got around this by creating a directory structure on my local Ubuntu computer that mirrored my GitHub Actions CI (`/home/runner/work/plenti/`). In the GitHub Action step I cloned that repo up one directory to avoid a dirty git state that breaks the build if you clone it into your working project directory - I suppose I could even move it up another directory to make the repo general purpose for other folks. 

Then just make sure to break `.goreleaser.yml` into multiple builds, for example if building Linux and Darwin:
```yml
builds:
- id: linux-build
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  ignore:
  - goos: linux
    goarch: 386
- id: darwin-build
  ldflags:
  - -s
  env:
  - CGO_ENABLED=1
  - CC=/home/runner/work/plenti/plenti-osxcross/target/bin/o64-clang
  - CXX=/home/runner/work/plenti/plenti-osxcross/target/bin/o64-clang++
  goos:
  - darwin
  ignore:
  - goos: darwin
    goarch: 386
```
