### ISSUE TITLE
Question: How to authenticate in Docker hub?

### ISSUE THREAD

**Issue by vgarvardt** [goreleaser/goreleaser-action#235]
Hi.

I'm trying to build a release and a docker image with GoReleaser using GH Actions. Building binaries works totally fine for me, but docker image fails to be pushed with:

```
release failed after 132.78s error=docker images: failed to publish artifacts: failed to push docker image: 
The push refers to repository [docker.io/hellofreshtech/kandalf]
```

e.g. https://github.com/hellofresh/kandalf/runs/980790191?check_suite_focus=true

The pipeline is available at https://github.com/hellofresh/kandalf/blob/master/.github/workflows/release.yml, the main part is:

```
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
```

When I use GoReleaser locally in the container with the same credentials - I see a message that login to docker was successful (or failed if creds are invalid). I tried to look at the code of the action but did not find if it passes env vars to the releaser exec.

```
❯ docker run --rm -it -v ${PWD}:/app -w /app -e GITHUB_TOKEN=*** -e DOCKER_USERNAME=hellofreshtech -e DOCKER_PASSWORD=*** goreleaser/goreleaser:latest release --rm-dist
Login to the docker...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

   • releasing...
   • loading config file       file=.goreleaser.yml
...
```
