### ISSUE TITLE
picked incorrect tag for release

### ISSUE THREAD

**Issue by theganyo** [goreleaser/goreleaser-action#238]
Using the following config:
```
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # semver v1.0.0-beta.2

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
goreleaser failed to use the correct tag.

1. I had tagged a `v1.1.0-rc.1` and goreleaser created a proper release.
2. I tagged `v1.1.0` on the same commit... and goreleaser re-created the `v1.1.0-rc.1` release.

My expectation was that it create a new release on the `v1.1.0` label.
