### ISSUE TITLE
Install only option

### ISSUE THREAD

**Issue by kristofferahl** [goreleaser/goreleaser-action#250]
Thanks for a great project!

Would it be possible to add an "install only" option so that gorelease could be used in the following steps?
In our project, we use a script in our release pipeline and I had hoped to use this action to install goreleaser before running our own script.

```yaml
-
  name: Setup GoReleaser
  uses: goreleaser/goreleaser-action@v2
  with:
    version: v0.145.0
    install-only: true
```

The expected outcome of using something like the above would be that goreleaser would be installed and added to the path, allowing goreleaser to be called from scripts in a pipeline.

Let me know if you need additional information.
