### ISSUE TITLE
Change build output name

### ISSUE THREAD

**Issue by Integralist** [goreleaser/goreleaser-action#264]
Hi, likely a silly question but I couldn't seem to locate the information for how to change the `go build` output filename? e.g. it generates a binary that's named the same as my repo but I'd like the name of the generated binary to be different to that.

I'm presuming I don't need to install goreleaser and run `goreleaser init` to generate a `.goreleaser.yml` to handle that?

I currently have just the single actions file: `.github/workflows/tag_release.yml`

```yml
name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.x'
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
        workdir: ./cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks!
