### ISSUE TITLE
Workflow error: git executable not found.

### ISSUE THREAD

**Issue by gianlucamazza** [goreleaser/goreleaser-action#266]
Hello,

I am having problems running my github actions CI both locally and github.
Actually I get this error running the following

```
$ act -v --env-file .env -s GITHUB_TOKEN
```

```
| ✅ GoReleaser installed successfully
| 📂 Using ./cmd/certyphoto/ as working directory...
[Release Go project/GoReleaser build]   ❗  ::error::Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[Release Go project/GoReleaser build]   ❌  Failure - Run GoReleaser
DEBU[0089] exit with `FAILURE`: 1                       
Error: exit with `FAILURE`: 1
```

My workflow:
```
name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: setup env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
          workdir: ./cmd/certyphoto/
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

```

The project is hosted on a private github repository. 
My main.go is in; ./cmd/certyphoto/main.go
Don't know what to try more.. :-)
