### ISSUE TITLE
hook failed: go mod download: exit status 1

### ISSUE THREAD

**Issue by Mr-xn** [goreleaser/goreleaser-action#268]
use alone action file can release success
> .github/workflows/go.yml 
```
name: Go

on:
  create:
    tags:
    - v*


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
but,default release not build for windows ,i want to build for windwos,so use the `.goreleaser.yml`
```
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64

archives:
  -
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
```
action run failed with the error：
```
✅ GoReleaser version found: v0.159.0
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.159.0/goreleaser_Linux_x86_64.tar.gz...
📦 Extracting GoReleaser...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/6f3ed5c7-943d-4dd5-a664-ec9a561a19ef -f /home/runner/work/_temp/f2e938e1-13ee-406e-96e1-157300492ed3
✅ GoReleaser installed successfully
✅ v1.1 tag found for commit '64f29c4'
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.159.0/x64/goreleaser release --rm-dist
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v1.1, commit 64f29c4121330e4fc9753bbd879436d963b034e7
   • parsing tag      
   • running before hooks
      • running go mod download
   ⨯ release failed after 0.03s error=hook failed: go mod download: exit status 1; output: go mod download: no modules specified (see 'go help mod download')

Error: The process '/opt/hostedtoolcache/goreleaser-action/0.159.0/x64/goreleaser' failed with exit code 1
```
have any error with my `.yaml` or other ways to build for windwos with gtihub action ?
thanks u !
