### ISSUE TITLE
add extra file to release files

### ISSUE THREAD

**Issue by Ja7ad** [goreleaser/goreleaser-action#314]
How do I add extra files to the released files when using a goreleaser action?

```yaml
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
```
