### ISSUE TITLE
Need multiple GH Tokens for local and remote publishing

### ISSUE THREAD

**Issue by displague** [goreleaser/goreleaser-action#322]
Because GH PAT can not be repository limited, they grant too much power and users may wish to create separate GH robot accounts with limited access (to the tap repo).

In this situation, when publishing a brew tap update, goreleaser will need one GH token to update the local project's build artifacts and create a release, and then a second GH token to publish the brew tap updates.

If it were possible to break the release process up into multiple phases, a first phase could publish local artifacts with the first token and a separate phase could apply tap updates using the second token.

If multiple tokens could be provided (and their purposes specified), then the existing single execution could be used for both phases.

**Comment by caarlos0** [comment]
this is already possible, you can set:

```yaml
brews:
  - tap:
      owner: caarlos0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
```

and pass both `GITHUB_TOKEN` and `HOMEBREW_TAP_GITHUB_TOKEN` envs, which can be the same token or different ones :)
