### ISSUE TITLE
AUR with SSH private key is considered invalid

### ISSUE THREAD

**Issue by Integralist** [goreleaser/goreleaser-action#326]
I have a SSH private key exposed as a GitHub Actions secret, and we assign it to an environment variable called `AUR_KEY` which is passed to goreleaser...

```yaml
    - name: "Run GoReleaser"
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v1.5.0
        args: release --rm-dist
      env:
        AUR_KEY: '${{ secrets.AUR_KEY }}'
        GOVERSION: ${{ env.GOVERSION }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
```

But when goreleaser runs it returns an error about the format being invalid...

```
⨯ release failed after 266.76s error=arch user repositories: failed to publish artifacts: failed to setup local AUR repo: "clone ssh://aur@aur.archlinux.org/REDACTED.git REDACTED" failed: Cloning into 'REDACTED'...
Failed to add the host to the list of known hosts (/home/runner/.ssh/known_hosts).
Load key "/tmp/id_1940525837": invalid format
aur@aur.archlinux.org: Permission denied (publickey).
fatal: Could not read from remote repository.
```

We tried running goreleaser locally and found that passing the SSH key in an environment variable didn't work but if we set the environment variable to the specific path (e.g. `~/.ssh/aur`) then it did work.

We tried to replicate this using the goreleaser GitHub Actions but found that we can't create a file because of a 'dirty state'...

```yaml
    # Passing the raw SSH private key causes an error:
    # Load key "/tmp/id_*": invalid format
    #
    # Testing locally we discovered that storing in a file and passing the file path works.
    - name: "Store AUR_KEY in local file"
      run: echo '${{ secrets.AUR_KEY }}' > '${{ github.workspace }}/aur_key'
    - name: "Run GoReleaser"
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v1.5.0
        args: release --rm-dist
      env:
        AUR_KEY: '${{ github.workspace }}/aur_key'
        GOVERSION: ${{ env.GOVERSION }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
```

Which produces this error...

```
Please check in your pipeline what can be changing the following files:
?? aur_key
```

**Comment by caarlos0** [comment]
is it possible that you are adding an extra new line to the secret? 

in any case, to be sure, we should probably trim those...

**Comment by Integralist** [comment]
@caarlos0 Thanks for the info. 

I've already double checked the secret value and it has no leading/trailing spaces...

```
-----BEGIN OPENSSH PRIVATE KEY-----
REDACTED
-----END OPENSSH PRIVATE KEY-----
```

It's hard to tell if the GitHub Actions running is doing anything odd when interpolating the value when I use it like:

```
AUR_KEY: '${{ secrets.AUR_KEY }}'
```

> **NOTE**: I've also tried using double quotes instead of single quotes and it still didn't work. 

As noted in the issue description we previously tried writing the key to a file and the output of that operation (before it subsequently failed due to a dirty state) was:

```
echo '***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***' > '/home/runner/work/***/***/aur_key'
``` 

...notice how there is no leading/trailing space, or so it seems at least. The obfuscating of the value and producing asterisks `***` _could_ still mean there is whitespace but that too is being obfuscated.

I've attempted to trim leading/trailing whitespace as demonstrated below...

```yaml
    - name: "Trim Private AUR_KEY"
      id: aurkey
      run: |
        KEY="${{ secrets.AUR_KEY }}"
        TRIMMED=$(echo -e "${{ secrets.AUR_KEY }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        echo ::set-output name=AUR_KEY_TRIMMED::${TRIMMED}
    - name: "Run GoReleaser"
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v1.5.0 # goreleaser version (NOT goreleaser-action version)
        args: release --rm-dist
      env:
        AUR_KEY: '${{ steps.aurkey.outputs.AUR_KEY_TRIMMED }}'
        GOVERSION: ${{ env.GOVERSION }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
```

But this instead results in the following error...

```
⨯ release failed after 249.51s error=arch user repositories: failed to publish artifacts: key "*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***" does not exist
```

The end of that error `key ... does not exist` makes me wonder if my trimming logic is broken and the persisted variable `AUR_KEY_TRIMMED` is being passed an empty value (but if so the fact the error shows a bunch of obfuscated asterisks makes me think a value was successfully assigned)?

I'm not sure if there's another way to trim the value?

**Comment by Integralist** [comment]
Alternatively do you know of a way to write the yaml/step(s) to store the secret into a file which works (i.e. doesn't produce a dirty state)?

**Comment by Integralist** [comment]
I should add that, when getting the `key ... does not exist` error I decided to change the code to use double quotes:

```diff
- echo ::set-output name=AUR_KEY_TRIMMED::${TRIMMED}
+ echo ::set-output name=AUR_KEY_TRIMMED::"${TRIMMED}"
```

And although it's the same error we can see the number of asterisks dropped to just one lines worth it would appear:

```
⨯ release failed after 261.48s error=arch user repositories: failed to publish artifacts: key "***" does not exist
```

This would _suggest_ that the logic for trimming the leading/trailing white space is valid.

**Comment by Integralist** [comment]
Hmm, I've just checked the goreleaser code base for this `key ... does not exist` error ([source](https://github.com/goreleaser/goreleaser/blob/6ec690723e36074e9f5df0b7ba6d88bbf34127c4/internal/pipe/aur/aur.go#L462-L464)) and the error actually indicates that the key has failed to be parsed using `ssh.ParsePrivateKey` so that suggests the trimming logic is incorrect.

**Comment by crazy-max** [comment]
I think 

```yaml
      env:
        AUR_KEY: ${{ secrets.AUR_KEY }}
        GOVERSION: ${{ env.GOVERSION }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
```

would have been fine. As you pointed out in the source code of GoReleaser, it excepts a file or the private key in plain text.
