### ISSUE TITLE
choco not working in actions

### ISSUE THREAD

**Issue by shotah** [goreleaser/goreleaser-action#381]
choco not available on Ubuntu and goreleaser/goreleaser-action@v3
```bash
  • chocolatey packages
    • packing                                        nuspec=dist/forgecli.choco/forgecli.nuspec
  ⨯ release failed after 1m36s               error=failed to generate chocolatey package: exec: "choco": executable file not found in $PATH: 
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.13.1/x64/goreleaser' failed with exit code 1
```

Current actions files, tempted to swapt it to windows, and the choco actions, but I don't think that will solve it either.
```yaml
on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: publish-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          PUSH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          CHOCOKEY: ${{ secrets.CHOCOKEY }}
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
```

One option maybe to move to nuget command which IS available on linux. Code I've used on Linux builders in the past:
```powershell
...
Function Test-PackageNotExist( $xmlobj )
{
    Return [string]::IsNullOrEmpty(( nuget list $xmlobj.id -source nexus -allversions | select-string "$($xmlobj.id).*$($xmlobj.version)" ))
}

Function Get-MetaData( $nuspec )
{
    return ([xml](Get-Content $nuspec.FullName)).package.metadata
}

Function Build-ChocoPackage( $nuspec )
{
    nuget pack $nuspec.FullName -NoPackageAnalysis
}

Function Push-ChocoPackage( $nupkg )
{
    nuget push $nupkg.FullName -timeout 1200 -Source $script:RepoName -SkipDuplicate
}
...
```
