### ISSUE TITLE
cannot find GoReleaser latest version

### ISSUE THREAD

**Issue by till** [goreleaser/goreleaser-action#389]
This randomly happened just now:

```yaml
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --rm-dist
      - name: Run Tests
        run: go test -v ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Error message:

```log
  Run goreleaser/goreleaser-action@v4
  with:
    args: build --snapshot --single-target --rm-dist
    distribution: goreleaser
    version: latest
    workdir: .
    install-only: false
  env:
    GOPRIVATE: github.com/org/repo
    DOWNLOAD_PACKAGE_TOKEN: ***
    GITHUB_TOKEN: ***
Error: Cannot find GoReleaser latest release
```

**Comment by graytonio** [comment]
I just had the same issue

**Comment by graytonio** [comment]
Trying to fix to a version also appears broken
```yaml
- uses: goreleaser/goreleaser-action@v4
    with:
      distribution: goreleaser
      version: v1.14.1
      args: release --rm-dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
```
with:
    distribution: goreleaser
    version: v1.1[4](https://github.com/graytonio/zoltan-bot/actions/runs/4029061823/jobs/6926570684#step:6:4).1
    args: release --rm-dist
    workdir: .
    install-only: false
  env:
    GITHUB_TOKEN: ***
  
Error: Cannot find GoReleaser v1.14.1 release
```
