### ISSUE TITLE
"failed to build for" error only in Github Action

### ISSUE THREAD

**Issue by danawoodman** [goreleaser/goreleaser-action#40]
`goreleaser release --rm-dist` works fine locally but when I attempt to use the Github Action I get errors like the following:

```
##[error]   ⨯ release failed after 0.12s error=failed to build for windows_amd64: main.go:4:2: cannot find package "github.com/foo/bar/cmd" in any of:
	/opt/hostedtoolcache/go/1.10.8/x64/src/github.com/foo/bar/cmd (from $GOROOT)
	/home/runner/go/src/github.com/foo/bar/cmd (from $GOPATH)

##[error]The process '/home/runner/work/_temp/a863cb99-f622-4bb0-8758-b06964d5df78/goreleaser' failed with exit code 1
##[error]Node run failed with exit code 1
```

(note I've replaced my repo/project with `foo/bar` above)

The actual "failed build" message is not always the same OS/Arch (sometimes its Linux+Arm etc).

Here is my actions file:

```yaml
name: Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@master
      - name: Install upx
        run: sudo apt install upx -y
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Am I missing something that I need to setup?

Also, I assum `GITHUB_TOKEN` is provided by the Github Actions runtime automatically?

Thanks!

**Comment by crazy-max** [comment]
@danawoodman Looks like your `foo/bar` is private, right?

**Comment by danawoodman** [comment]
@crazy-max yes my repo is private

**Comment by crazy-max** [comment]
@danawoodman Ok, is `foo/bar` in the same org/user on GitHub? Also can you give me your `.goreleaser.yml` config please?

**Comment by danawoodman** [comment]
@crazy-max what do you mean "same org/user"? The action and goreleaser config are all part of the same repo if that is what you're asking

Here is my config:

```yaml
# Documentation: http://goreleaser.com
builds:
  - id: foobar
    binary: foobar
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.key={{ .Env.ENCRYPTION_KEY }}
    env:
      - CGO_ENABLED=0
    hooks:
      post: /bin/sh ./scripts/release-build.sh
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
release:
  github:
    owner: foo
    name: bar
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
env_files:
  github_token: ~/.github-token
```

Thanks for any help!

**Comment by crazy-max** [comment]
Ok this is on the same private repo. Do you have an idea @caarlos0? Maybe that could come from [GOPROXY or GOPRIVATE](https://golang.org/doc/go1.13#modules) or `go.mod` does not have `github.com/foo/bar` as module name.

**Comment by danawoodman** [comment]
@crazy-max I am able to release no problem on my CLI but as soon as I run in Github Actions it fails so I assume it has to do with the action having a bug or maybe an env var not being set?

go.mod has the right package name. I haven't noticed any other issues when releasing

**Comment by crazy-max** [comment]
@danawoodman Can you remove `env_files:` and try again? I think it overrides `GITHUB_TOKEN` env.

**Comment by danawoodman** [comment]
@crazy-max if I remove that how will I load in the contents of the env file?

I will remove it and try again to test

**Comment by danawoodman** [comment]
@crazy-max still getting the same errors :/

**Comment by crazy-max** [comment]
@danawoodman 

> if I remove that how will I load in the contents of the env file?

I don't know the content of this file if you don't tell me but I asusme it's the GitHub Token. If so, it is already provided through the action env: `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`.

> still getting the same errors :/

I have created a private repo to try to reproduce your behavior and everything works fine for me:

![image](https://user-images.githubusercontent.com/1951866/69712224-c327e580-1102-11ea-8905-dec0e4c683c2.png)

![image](https://user-images.githubusercontent.com/1951866/69712247-cb802080-1102-11ea-83e6-01ac4002fc86.png)

![image](https://user-images.githubusercontent.com/1951866/69712270-d470f200-1102-11ea-8f1a-087cbc8f96cc.png)

![image](https://user-images.githubusercontent.com/1951866/69712303-e2267780-1102-11ea-8336-b020cc6da409.png)

![image](https://user-images.githubusercontent.com/1951866/69712392-05e9bd80-1103-11ea-85ac-ce6cab0eb348.png)

![image](https://user-images.githubusercontent.com/1951866/69712407-100bbc00-1103-11ea-892a-82d37a3cafef.png)

Here is the project if you want to try out: [test-action.zip](https://github.com/goreleaser/goreleaser-action/files/3896155/test-action.zip)

**Comment by danawoodman** [comment]
@crazy-max thanks for spending all this time on this. I made a few changes that I noticed in your config file that seems to have fixed the issue including:

`.goreleaser.yml`:

```
env:
  - GO111MODULE=on
 before:
   hooks:
    - go mod download
# ... under jobs:
        with:
          go-version: 1.13.x
```

One of them seems to have done the trick!
