### ISSUE TITLE
Env variables not available in post-build hooks

### ISSUE THREAD

**Issue by wbrefvem** [goreleaser/goreleaser-action#402]
Locally, I can specify the following hook:
```
build:
  hooks:
    post: 
      - chown <uid>:<gid> {{ .Path }}
```

As expected, GoReleaser runs the following:
```
chown <uid>:<gid> /path/to/my/binary
```
However, in the GitHub action, using the same GoReleaser version (1.16.0), the `.Path` variable does not come through, and GoReleaser runs:
```
chown <uid>:<gid>
```
And so the command fails.
