### ISSUE TITLE
Cannot use SSH private key secret as it is being treated as filename

### ISSUE THREAD

**Issue by lukasmalkmus** [goreleaser/goreleaser-action#440]
I'm trying to release to AUR.

`.goreleaser.yaml` uses the SSH private key like this:

```
private_key: "{{ .Env.AUR_KEY }}"
```

My workflow looks something like this:

```
- uses: goreleaser/goreleaser-action@v5
  with:
    args: release
  env:
    GITHUB_TOKEN: ${{ github.token }}
    HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
    AUR_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
```

However, the actions error with this message from GoReleaser:

``` 
* arch user repositories: git: could not stat private_key: stat ***
```

It looks like the SSH private key is being treated as a filename?
