### ISSUE TITLE
How can I use goreleaser from master?

### ISSUE THREAD

**Issue by bartekpacia** [goreleaser/goreleaser-action#453]
I tried this but it doesn't work:

```yaml
- name: Run GoReleaser
  uses: goreleaser/goreleaser-action@v5
  with:
    version: master
    args: release --clean
  env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
    AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
```

<img width="1033" alt="Screenshot 2024-03-21 at 23 46 35" src="https://github.com/goreleaser/goreleaser-action/assets/40357511/8009b1ab-e08e-4549-876b-3ba97f90d685">

Use case: take advantage of the fixes merged to `master` but not yet released (such as https://github.com/goreleaser/goreleaser/issues/4679)
