### ISSUE TITLE
Is there a way to avoid fetch-depth:0

### ISSUE THREAD

**Issue by thomaspoignant** [goreleaser/goreleaser-action#457]
I am working with a pretty big repository in terms of activity, and I follow the requirement of using checkout with `fetch-depth: 0`

```yaml
 -
    name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0
```

But since my repository has a lot of history (+ considering big size), it can take up to 10 min just for the checkout _([example](https://github.com/thomaspoignant/go-feature-flag/actions/runs/8740459486/job/23984208254)._

Is there a way to use the goreleaser action without having to set `fetch-depth: 0` before the action and to still have a proper result?
