### ISSUE TITLE
failed to change file path in github actions

### ISSUE THREAD

**Issue by pibigstar** [goreleaser/goreleaser-action#62]
Hi,

I want build two binaries, one is `go-proxy/client/client.go`, another is `go-proxy/server/server.go`

**my release.yml**
```yml
name: Release
on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - name: pwd
        run: pwd

      - name: Create client on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release --rm-dist
          workdir: ./client/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create server on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**the github actions result, why the pwd is duplicated `go-proxy` ?**

![image](https://user-images.githubusercontent.com/33958530/71538680-0bd4f780-296a-11ea-90e5-953a7aee6b3f.png)
