### ISSUE TITLE
Docker authorization?

### ISSUE THREAD

**Issue by 4nte** [goreleaser/goreleaser-action#90]
I can't find any info in the documentation on how to provide Docker credentials to the goreleaser Action.
Is this not supported?

**Comment by crazy-max** [comment]
Hi @4nte,

This workflow should work:

```yml
name: goreleaser

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Docker Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Clear
        if: always() && startsWith(github.ref, 'refs/tags/')
        run: |
          rm -f ${HOME}/.docker/config.json
```

The `Docker Login` step is what you want in your case.
